name: usesend-prod

services:
  postgres:
    image: postgres:16
    container_name: usesend-db-prod
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: usesend-redis-prod
    restart: always
    # ports:
    #   - "6379:6379"
    volumes:
      - cache:/data
    command: ["redis-server", "--maxmemory-policy", "noeviction"]

  usesend:
    image: usesend/usesend:latest
    container_name: usesend
    restart: always
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    environment:
      - PORT=${PORT:-3000}
      - DATABASE_URL=${DATABASE_URL:?err}
      - NEXTAUTH_URL=${NEXTAUTH_URL:?err}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY:?err}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY:?err}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:?err}
      - GITHUB_ID=${GITHUB_ID:?err}
      - GITHUB_SECRET=${GITHUB_SECRET:?err}
      - REDIS_URL=${REDIS_URL:?err}
      - NEXT_PUBLIC_IS_CLOUD=${NEXT_PUBLIC_IS_CLOUD:-true}
      - API_RATE_LIMIT=${API_RATE_LIMIT:-1}
      - SMTP_HOST=${SMTP_HOST:-smtp.usesend.com}
      - SMTP_USER=${SMTP_USER:-usesend}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FOUNDER_EMAIL=${FOUNDER_EMAIL}
      - FROM_EMAIL=${FROM_EMAIL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - UNSEND_API_KEY=${UNSEND_API_KEY}
      - USESEND_API_KEY=${USESEND_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_BASIC_PRICE_ID=${STRIPE_BASIC_PRICE_ID}
      - STRIPE_BASIC_USAGE_PRICE_ID=${STRIPE_BASIC_USAGE_PRICE_ID}
      - STRIPE_LEGACY_BASIC_PRICE_ID=${STRIPE_LEGACY_BASIC_PRICE_ID},
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - USESEND_BASE_URL=${USESEND_BASE_URL}
      - S3_COMPATIBLE_ACCESS_KEY=${S3_COMPATIBLE_ACCESS_KEY},
      - S3_COMPATIBLE_SECRET_KEY=${S3_COMPATIBLE_SECRET_KEY},
      - S3_COMPATIBLE_API_URL=${S3_COMPATIBLE_API_URL},
      - S3_COMPATIBLE_PUBLIC_URL=${S3_COMPATIBLE_PUBLIC_URL},
      - S3_COMPATIBLE_BUCKET=${S3_COMPATIBLE_BUCKET},
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  database:
  cache:
  storage:
