name: Publish Docker

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the action on"
        default: "main"
        required: true

jobs:
  build_and_publish_platform_containers:
    name: Build and publish platform containers
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # - linux/arm64
        app:
          - name: usesend
            dockerfile: ./docker/Dockerfile
            context: .
          - name: smtp-proxy
            dockerfile: ./apps/smtp-server/Dockerfile
            context: ./apps/smtp-server

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        env:
          BUILD_PLATFORM: ${{ matrix.platform }}
          APP: ${{ matrix.app.name }}
          DOCKER_FILE: ${{ matrix.app.dockerfile }}
          CONTEXT: ${{ matrix.app.context }}
        run: |
          APP_VERSION="$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')"
          GIT_SHA="$(git rev-parse HEAD)"
          BUILD_ARCH="${BUILD_PLATFORM#*/}"

          docker build \
            --platform "$BUILD_PLATFORM" \
            -f "$DOCKER_FILE" \
            --progress=plain \
            -t "bitmesh/$APP-$BUILD_ARCH:latest" \
            -t "bitmesh/$APP-$BUILD_ARCH:$GIT_SHA" \
            -t "bitmesh/$APP-$BUILD_ARCH:$APP_VERSION" \
            -t "ghcr.io/mmihalev/$APP-$BUILD_ARCH:latest" \
            -t "ghcr.io/mmihalev/$APP-$BUILD_ARCH:$GIT_SHA" \
            -t "ghcr.io/mmihalev/$APP-$BUILD_ARCH:$APP_VERSION" \
            "$CONTEXT"

      - name: Push the docker image to DockerHub
        run: |
          BUILD_ARCH="${BUILD_PLATFORM#*/}"
          docker push --all-tags "bitmesh/$APP-$BUILD_ARCH"
        env:
          BUILD_PLATFORM: ${{ matrix.platform }}
          APP: ${{ matrix.app.name }}

      - name: Push the docker image to GitHub Container Registry
        run: |
          BUILD_ARCH="${BUILD_PLATFORM#*/}"
          docker push --all-tags "ghcr.io/mmihalev/$APP-$BUILD_ARCH"
        env:
          BUILD_PLATFORM: ${{ matrix.platform }}
          APP: ${{ matrix.app.name }}

  create_and_publish_manifest:
    name: Create and publish manifest
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: build_and_publish_platform_containers
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push DockerHub manifest
        run: |
          APP_VERSION="$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')"
          GIT_SHA="$(git rev-parse HEAD)"

          for APP_NAME in usesend smtp-proxy; do
            docker manifest create \
              bitmesh/$APP_NAME:latest \
              --amend bitmesh/$APP_NAME-amd64:latest
              # --amend bitmesh/$APP_NAME-arm64:latest

            docker manifest create \
              bitmesh/$APP_NAME:$GIT_SHA \
              --amend bitmesh/$APP_NAME-amd64:$GIT_SHA
              # --amend bitmesh/$APP_NAME-arm64:$GIT_SHA

            docker manifest create \
              bitmesh/$APP_NAME:$APP_VERSION \
              --amend bitmesh/$APP_NAME-amd64:$APP_VERSION
              # --amend bitmesh/$APP_NAME-arm64:$APP_VERSION

            docker manifest push bitmesh/$APP_NAME:latest
            docker manifest push bitmesh/$APP_NAME:$GIT_SHA
            docker manifest push bitmesh/$APP_NAME:$APP_VERSION
          done

      - name: Create and push GitHub Container Registry manifest
        run: |
          APP_VERSION="$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')"
          GIT_SHA="$(git rev-parse HEAD)"

          for APP_NAME in usesend smtp-proxy; do
            docker manifest create \
              ghcr.io/mmihalev/$APP_NAME:latest \
              --amend ghcr.io/mmihalev/$APP_NAME-amd64:latest
              # --amend ghcr.io/mmihalev/$APP_NAME-arm64:latest

            docker manifest create \
              ghcr.io/mmihalev/$APP_NAME:$GIT_SHA \
              --amend ghcr.io/mmihalev/$APP_NAME-amd64:$GIT_SHA
              # --amend ghcr.io/mmihalev/$APP_NAME-arm64:$GIT_SHA

            docker manifest create \
              ghcr.io/mmihalev/$APP_NAME:$APP_VERSION \
              --amend ghcr.io/mmihalev/$APP_NAME-amd64:$APP_VERSION
              # --amend ghcr.io/mmihalev/$APP_NAME-arm64:$APP_VERSION

            docker manifest push ghcr.io/mmihalev/$APP_NAME:latest
            docker manifest push ghcr.io/mmihalev/$APP_NAME:$GIT_SHA
            docker manifest push ghcr.io/mmihalev/$APP_NAME:$APP_VERSION
          done
